### ISSUE TITLE
Fork and Edit 404

### ISSUE THREAD

**Issue by slhenry** [w3c/EasyChecks#106]
on the page https://www.w3.org/WAI/test-evaluate/preliminary/

"Fork and Edit on GitHub" gives 404

(from @hidde )

**Comment by yatil** [comment]
As mentioned in our 1:1, I moved the file to content/index.md & updated the path accordingly:

https://github.com/w3c/EasyChecks/commit/6415fbebcda52c588b9e216cadb94317d9aaab5a#diff-a6ab42ad501cfe5f7290dcdbeda6ce90

Because there were no significant changes in the file, I did not publish that update. I’ll do it now.

**Comment by hidde** [comment]
Cheers, thanks for updating this issue., I was just verifying what was wrong and couldn't find it (because it is no longer wrong 👍 ).

**Comment by yatil** [comment]
Is now fixed.
