### ISSUE TITLE
Cover moving/animated content

### ISSUE THREAD

**Issue by yatil** [w3c/EasyChecks#23]
Branching from issue #1 – What do we need to address moving or animated content in Easy Checks?

**Comment by slhenry** [comment]
# Moving Content

Moving content includes "carousels" such as below, videos, ads, auto-updating stock tickers, and more. Users need to be able to control moving content, especially some people with attention deficit or visual processing disorders.
[ https://www.w3.org/WAI/tutorials/carousels/animations/#c ]

There are two potential accessibility problems with moving content:

1. Getting moving information &mdash; Some people read and process information slowly. The content may disappear before people have time to read it. Some people have trouble tracking moving objects.

2. Distraction from moving content &mdash; Moving content can make focusing and reading elsewhere difficult; that is, people cannot focus on some content because the movement in another area of the web page grabs their attention.

## What to check for:

- Check if there is any moving, blinking, or scrolling information that starts automatically and lasts more than five seconds. If there is, check that there is a way for the user to pause, stop, or hide the movement.
- Check if there is any auto-updated information (such as stock price). If there is, check that there is a way for the user to pause, stop, or hide the updated information, or for the user to control the frequency of the update.

## To learn more about moving content

- [Pause, Stop, Hide](https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-pause.html) - Understanding Success Criterion 2.2.2 for WCAG 2.0 (Level A)
- [Carousel Animations](https://www.w3.org/WAI/tutorials/carousels/animations/) – WAI Web Accessibility Tutorial

**Comment by sharronrush** [comment]
Excellent presentation of the issue, thanks Shawn!
2 things:
1. When you say "carousels such as below" do you mean to include the graphic within the page itself or just link to it? Since we link to the Carousels Tutorial in the followup neither may be necessary. Not a strong feeling, just a note. 

2. "Getting moving information" is an awkward phrase, IMO. Suggest "Understanding moving information" or "Reading moving text" or something less confusing.

Overall, really great, thanks!

**Comment by slhenry** [comment]
Thanks for quick comments, Sharron!

I added "put this carousel here:" above to make that clear. I'm not sure whether or not we want it there -- it might be too attention-grabbing. ;-)

+1 to "Understanding moving information" -- I updated it above.

**Comment by vuxcaleb** [comment]
@slhenry This is fantastic!!!

**Comment by vuxcaleb** [comment]
Pull request with added Moving Content check has been made.

**Comment by slhenry** [comment]
Discussion moved to https://github.com/w3c/EasyChecks/issues/27
