### ISSUE TITLE
[Easy Checks] - Multimedia /Media alternatives

### ISSUE THREAD

**Issue by HerinHentry** [w3c/EasyChecks#69]
WCAG mentions audio & video as media alternatives in [1.2.3](http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-audio-desc.html) & [1.2.8](http://www.w3.org/TR/UNDERSTANDING-WCAG20/media-equiv-text-doc.html). 

As multimedia refers to text, print media as well, I think we can be consistent here using the same terminology as WCAG. Please consider this suggestion to keep the key terminologies consistent across.

![meida alternative](https://cloud.githubusercontent.com/assets/15111528/21313181/6b5cdcf4-c644-11e6-9e96-1fa543856fda.png)

**Comment by slhenry** [comment]
Thanks for all your comments, @HerinHentry !

I'm not sure I understand your suggestion. Are you suggesting we change the heading of "Multimedia (video, audio) alternatives" to "Media Alternatives"?

If so, I think EOWG would prefer to leave "Multimedia" since that is more common language. For Easy Checks, we tried to use more common terminology even if it's not an exact match to WCAG.

**Comment by HerinHentry** [comment]
I agree to your comments @slhenry . I was looking for consistency.

**Comment by slhenry** [comment]
Discussed in [13 Jan telecon](https://www.w3.org/2017/01/13-eo-minutes.html#item03) and put on weekly [survey](https://www.w3.org/2002/09/wbs/35532/EO-Weekly-13-Jan-2017/results#xq1) for approval of resolutions.
