### ISSUE TITLE
Resize text checks: number of increments

### ISSUE THREAD

**Issue by Veyfeyken** [w3c/EasyChecks#70]
Hi,

> Incrementally increase text-only zoom:
In Windows, press Ctrl+[+] (the control key and the + key at the same time) 4 times
On Mac, press command+[+] (the Command key and the + key at the same time) 4 times

If the font-size is declared in relative units (%), it takes 5  increments to reach 200% in Chrome and 6 increments in Firefox according to my tests. I used [this page](http://gijs.anysurfer.be/test/resize.html) and `p{font-size:100%;}`.

**Comment by slhenry** [comment]
Thank you for the feedback!

I think Chrome doesn't do text-only zoom without an extension, so we don't list it.

In my Firefox on Windows it also takes 6 to get to 200%. I think I recall at the time that some only needed 4 times, and so we went with the lowest &mdash; given that Easy Checks is just a first review, not  definitive evaluation.

**EOWG folks: How about for your versions of Firefox and Safari?**

*If* it's 6 in all others tested, the I propose we just change "4 times" to "6 times".
*If* it's different, we could do something like:

> Incrementally increase text-only zoom:
> * In Windows, press Ctrl+[+] (the control key and the + key at the same time) several times to get to 200% zoom (which is 6 times in some browsers)
> * On Mac, press command+[+] (the Command key and the + key at the same time) several times to get to 200% zoom (which is 6 times in some browsers)

**Comment by slhenry** [comment]
[Current [Resize Text section](https://www.w3.org/WAI/eval/preliminary#resize)] Thanks for ideas in [13 Jan telecon](https://www.w3.org/2017/01/13-eo-minutes.html#item03).

The challenge is that it's different numbers of increments depending on your setup, *and* it's not easy to tell your zoom level.

_Here is a proposal &mdash; that still needs instructions in Safari:_

<p><strong>To check text-only zoom in Firefox, Safari, and some other browsers:</strong></p>
<ol>
  <li>Set zoom to text only. Depending on your browser:
    <ul>
      <li>From the menubar, select View &gt; Zoom &gt; Zoom Text Only.<br>
        Or, with the keyboard in Firefox: Alt+V, Z, T</li>
      <li>From the menubar, select View &gt; Zoom Text Only.<br>
        Or, with the keyboard in Safari: control+F2, V, return, ZZ</li>
    </ul>
  </li>
  <li>Increase zoom to 200%.
    <ul>
      <li>To incrementally increase zoom with the keyboard in Firefox, Safari, and most browsers:
        <ul>
          <li>Windows, press Ctrl+[+] <em>(hold down the control key and press the + key at the same time)</em>.</li>
          <li>On Mac, press command+[+] <em>(hold down the command key and the + key at the same time)</em>.</li>
        </ul>
      </li>
      Usually 4-6 key presses gets to 200%.
      <li>In Firefox, to check or set the zoom percent:</li>
      <ul>
        <li>Click the menu button on the right.<br>
          [img: https://support.cdn.mozilla.net/media/uploads/gallery/images/2014-02-06-12-50-57-fa7069.png]</li>
        <li>The customization menu, click the + button to zoom larger. The number before the + button is the current zoom percent.</li>
      </ul>
      <li>In Safari, to check or set the zoom percent:
        <ul>
          <li>@@</li>
        </ul>
      </li>
    </ul>
  </li>
</ol>

**Comment by haltersweb** [comment]
I would suggest adding a suggestion to use rem vs em for font sizing.  Rem is a little-known but powerful relative sizing unit that has been part of the CSS lexicon since the early days.  It is now universally supported (IE having been the hold-out until recent years) http://caniuse.com/#feat=rem

Rem is what we use at Comcast.  It gives greater control since it's relative to the document not the parent.

Here is what we have in our Comcast accessibility standards regarding rems:

**Relative Font Size**

Use **relative** units (rem preferably, otherwise em) to specify font sizes.  Do not use absolute units such as px to define font-size.

Using rem is preferable to using em when setting font size.  The rem unit defines the element's font-size relative to the <html> font size.  Using rem alleviates the unwanted changes to font sizes when em-defined elements are nested.

**Tip:** Calibrate your font size to 62.5% in the root (html) to ensure your rem size relates easily to px without complex calculations. 1.0rem => 10px, 1.2rem => 12px, 2.1rem => 21px, etc.

**Example**

```
html {
    font-size: 62.5%; /* calibrate 1.0rem = 10px */
    }
body {
    font-size: 1.3rem; /* =13px */
    }
.small {
    font-size: 1.1rem; /* =11px */
    }
```

**Comment by nitedog** [comment]
@haltersweb I think this could be very useful to consider for the [Tips for Getting Started with Web Accessibility](https://www.w3.org/WAI/gettingstarted/tips/) resource than this one.

**Comment by slhenry** [comment]
Agree that this kind of information fits better in Tips and not in Easy Checks - since Easy Checks is more about understanding evaluation, and Tips is more about instructing developers. @haltersweb  Here is link to [add issue for Tips](https://github.com/w3c/wai-quick-start/issues/new?title=[Tips%20for%20Getting%20Started%20with%20Web%20Accessibility]&body=This%20is%20a%20comment%20related%20to%20the%20page%20[Tips%20for%20Getting%20Started%20with%20Web%20Accessibility](//w3c.github.io/wai-quick-start/index.html))  :-)

**Comment by bakkenb** [comment]
Agree better fit for tips. Too complex for Easy Checks. 
I am good with @slhenry recommendation.

**Comment by hkramer** [comment]
As above, would pass on rems - too complex for this tool.

**Comment by susanatx** [comment]
I still think this level of "how to use your keyboard and browser" instructions is unnecessary. but I'll accept it.

**Comment by dboudreau** [comment]
@slhenry - Here goes. In Safari (MacOS X),
- to set the zoom percent to 200%: cmd+[+] (hold down the command key and the + key at the same time).
- to set the text resize to 200%: alt+cmd+[+] (hold down both keys and the + key at the same time).

5 key presses are needed to get to 200% in each case.

**Comment by vuxcaleb** [comment]
Thanks @dboudreau I will add this and make a pull request!

**Comment by yatil** [comment]
@haltersweb 

> html {
>    font-size: 62.5%; /* calibrate 1.0rem = 10px */
>   }

Note that this can have a negative impact on text resizing in certain instances. It is better to go from 1rem = 16px and calculate from there, especially as 16px is already on the lower end of readability these days.
