### ISSUE TITLE
Easy Checks - Broken links in pages

### ISSUE THREAD

**Issue by HerinHentry** [w3c/EasyChecks#76]
Hi, 

https://www.w3.org/WAI/EO/Drafts/eval/checks - Internal page anchors are broken and taking to w3 pages like https://www.w3.org/#structure

Page title
Image text alternatives ("alt text") (pictures, illustrations, charts, etc.)
Headings
Contrast ratio ("color contrast")
Resize Text
Keyboard access and visual focus
Forms, labels, and errors (including Search fields)
Flashing or Blinking Content
Multimedia (video, audio) alternatives
Basic Structure Check

**Comment by slhenry** [comment]
Thanks for taking the time to comment.

https://www.w3.org/WAI/EO/Drafts/eval/checks  is an internal draft. At the top is says: 
> This is an internal Editor's Draft. The main page is at www.w3.org/WAI/eval/preliminary

:-)

If you know how you got to the internal draft instead of the published page, please let us know and we'll see if there's anything we can do about it. We might also make the status more clear.

I checked the published page, and it looks like the links work there.

**Comment by HerinHentry** [comment]
Hi, My bad...Google search for preliminary checks came with the drafts. Not sure if we can do something about it. Thanks


Sent from my phone

-------- Original message --------
