### ISSUE TITLE
URI

### ISSUE THREAD

**Issue by slhenry** [w3c/EasyChecks#86]
current URI is https://www.w3.org/WAI/eval/preliminary
(because once upon a time, this page was called "Preliminary Review of Web Sites for Accessibility")

In-progress prototype has http://w3c.github.io/wai-website/test-evaluate/easychecks/

Given that we expect to change the title when we revise resource, and it might not end up being "Easy Checks", I mildly propose that we do not use "/easychecks/" and probably continue to use "/preliminary/"

**Comment by yatil** [comment]
We can use whatever we like, even the `/test-evaluate/` section is not a must. I don’t like “preliminary” because it is a complicated word and hard to understand, especially if you are not a native speaker.

[Synonyms for preliminary](http://www.thesaurus.com/browse/preliminary?s=t) adj introductory, initial:
exploratory, preparatory, prior, basic, first, fundamental, opening, pilot, primary, qualifying, readying, test, trial, elemental, elementary, inductive, initiatory, preceding, precursory, prefatory, preparing, primal
